name: Markdown Lint
run-name: MD/Lint

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - docs
  pull_request:
    branches:
      - main
      - docs
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v.4.4.0
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm install -g markdownlint-cli
      - name: Run Markdown Lint
        run: markdownlint ./*.md
